services:
  - type: web
    name: harper-ai-website-v3
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true

  # Alternative: Docker-based deployment
  # Uncomment below if you prefer Docker deployment
  # - type: web
  #   name: harper-ai-website-docker
  #   runtime: docker
  #   dockerfilePath: ./Dockerfile
  #   dockerContext: .
  #   healthCheckPath: /health
  #   envVars:
  #     - key: PORT
  #       value: 10000