services:
  - type: web
    name: harper-ai-marketing-website
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    branch: main
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000